version: '3.9'
services:
  app:
    image: app
    container_name: app11
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SELECTED_REPO: JPA
      SERVER_PORT: 8080
  app2:
    image: app
    container_name: app22
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      SELECTED_REPO: JDBC
      SERVER_PORT: 8090